### ISSUE TITLE
FileUtils.writeFile有问题

### ISSUE THREAD

**Issue by aosiwade** [zhengmingliang/ZmlTools#1]
@zhengmingliang 当路径不是绝对路径时，写入会有问题
![image](https://user-images.githubusercontent.com/63693172/79295036-46a76f00-7f0a-11ea-86b3-3284d992725a.png)

**Comment by zhengmingliang** [comment]
> @zhengmingliang 当路径不是绝对路径时，写入会有问题
> ![image](https://user-images.githubusercontent.com/63693172/79295036-46a76f00-7f0a-11ea-86b3-3284d992725a.png)

已修正 ，[详见此处 ](https://github.com/zhengmingliang/ZmlTools/blob/0b2f9e1c6418eec0a89db88c853bb97885fb6f39/src/main/java/top/wys/utils/FileUtils.java#L96)
